[versions]
# Platform expectations
paper = "1.17.1-R0.1-SNAPSHOT"

# Plugins
plotsquared = "6.2.0"
worldedit = "7.2.8"
dynmap = "3.2-beta-1"

# Third party
bstats = "2.2.1"

# Gradle plugins
shadow = "7.1.1"
bukkityml = "0.5.1"

[libraries]
# Platform expectations
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

# Plugins
plotsquared = { group = "com.plotsquared", name = "PlotSquared-Core", version.ref = "plotsquared" }
worldedit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version.ref = "worldedit" }
dynmapCore = { group = "us.dynmap", name = "DynmapCore", version.ref = "dynmap" }
dynmapApi = { group = "us.dynmap", name = "dynmap-api", version.ref = "dynmap" }

# Third party
bstatsBase = { group = "org.bstats", name = "bstats-base", version.ref = "bstats" }
bstatsBukkit = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
pluginyml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "bukkityml" }
